// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_resumes_upload_resumeSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_resumes-upload_resume'
} as const;

export const CareerProfilePublicSchema = {
    properties: {
        ai_provider: {
            type: 'string',
            maxLength: 50,
            title: 'Ai Provider',
            description: "AI provider used: 'gemini' or 'ollama'"
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            type: 'string',
            format: 'uuid',
            title: 'Resume Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        projects: {
            type: 'string',
            title: 'Projects'
        },
        experience: {
            type: 'string',
            title: 'Experience'
        },
        skills: {
            type: 'string',
            title: 'Skills'
        },
        extracted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Extracted At'
        }
    },
    type: 'object',
    required: ['ai_provider', 'id', 'resume_id', 'owner_id', 'projects', 'experience', 'skills', 'extracted_at'],
    title: 'CareerProfilePublic',
    description: 'Public response model for career profile'
} as const;

export const CareerProfileReadSchema = {
    properties: {
        ai_provider: {
            type: 'string',
            maxLength: 50,
            title: 'Ai Provider',
            description: "AI provider used: 'gemini' or 'ollama'"
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            type: 'string',
            format: 'uuid',
            title: 'Resume Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        projects: {
            items: {
                '$ref': '#/components/schemas/Project'
            },
            type: 'array',
            title: 'Projects'
        },
        experience: {
            items: {
                '$ref': '#/components/schemas/Experience'
            },
            type: 'array',
            title: 'Experience'
        },
        skills: {
            items: {
                '$ref': '#/components/schemas/SkillCategory'
            },
            type: 'array',
            title: 'Skills'
        },
        extracted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Extracted At'
        }
    },
    type: 'object',
    required: ['ai_provider', 'id', 'resume_id', 'owner_id', 'projects', 'experience', 'skills', 'extracted_at'],
    title: 'CareerProfileRead',
    description: 'Public response model with structured data (not JSON strings).'
} as const;

export const CareerProfileUpdateSchema = {
    properties: {
        projects: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Project'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projects'
        },
        experience: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Experience'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experience'
        },
        skills: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SkillCategory'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skills'
        }
    },
    type: 'object',
    title: 'CareerProfileUpdate',
    description: `Update model for career profile.
All fields are optional to allow partial updates.`
} as const;

export const ExperienceSchema = {
    properties: {
        company: {
            type: 'string',
            title: 'Company',
            description: 'Company name'
        },
        role: {
            type: 'string',
            title: 'Role',
            description: 'Job title/role'
        },
        duration: {
            type: 'string',
            title: 'Duration',
            description: "Time period, e.g., '2020-2023' or '2 years'"
        },
        responsibilities: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Responsibilities',
            description: 'Key responsibilities and achievements'
        }
    },
    type: 'object',
    required: ['company', 'role', 'duration', 'responsibilities'],
    title: 'Experience',
    description: 'Work experience entry from resume'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Title'
        },
        company: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Company'
        },
        url: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Url'
        },
        location: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Location'
        },
        description: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title', 'company', 'url', 'location', 'description'],
    title: 'JobCreate'
} as const;

export const JobPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Title'
        },
        company: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Company'
        },
        url: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Url'
        },
        location: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Location'
        },
        description: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'company', 'url', 'location', 'description', 'id', 'owner_id', 'status', 'created_at'],
    title: 'JobPublic'
} as const;

export const JobStatsSchema = {
    properties: {
        Draft: {
            type: 'integer',
            title: 'Draft',
            default: 0
        },
        Applied: {
            type: 'integer',
            title: 'Applied',
            default: 0
        },
        Shortlisted: {
            type: 'integer',
            title: 'Shortlisted',
            default: 0
        },
        Interviewing: {
            type: 'integer',
            title: 'Interviewing',
            default: 0
        },
        Offered: {
            type: 'integer',
            title: 'Offered',
            default: 0
        },
        Redirected: {
            type: 'integer',
            title: 'Redirected',
            default: 0
        },
        Waiting: {
            type: 'integer',
            title: 'Waiting',
            default: 0
        }
    },
    type: 'object',
    title: 'JobStats'
} as const;

export const JobUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        company: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        location: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'JobUpdate'
} as const;

export const JobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/JobPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'JobsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            description: 'Project name or title'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Brief description of what was built'
        },
        technologies: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Technologies',
            description: 'Technologies, languages, frameworks used'
        },
        impact: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Impact',
            description: 'Business impact or metrics if mentioned'
        }
    },
    type: 'object',
    required: ['title', 'description', 'technologies'],
    title: 'Project',
    description: 'Individual project extracted from resume'
} as const;

export const ResumePublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        raw_text: {
            type: 'string',
            title: 'Raw Text'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        upload_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upload Date'
        }
    },
    type: 'object',
    required: ['filename', 'raw_text', 'id', 'owner_id', 'upload_date'],
    title: 'ResumePublic'
} as const;

export const ResumesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ResumePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ResumesPublic'
} as const;

export const SkillCategorySchema = {
    properties: {
        category: {
            type: 'string',
            title: 'Category',
            description: "Skill category, e.g., 'Backend', 'Frontend', 'DevOps'"
        },
        skills: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills',
            description: 'List of skills in this category'
        }
    },
    type: 'object',
    required: ['category', 'skills'],
    title: 'SkillCategory',
    description: 'Categorized skills from resume'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;