// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_resumes_upload_resume = {
    file: (Blob | File);
};

/**
 * Public response model for career profile
 */
export type CareerProfilePublic = {
    /**
     * AI provider used: 'gemini' or 'ollama'
     */
    ai_provider: string;
    id: string;
    resume_id: string;
    owner_id: string;
    projects: string;
    experience: string;
    skills: string;
    extracted_at: string;
};

/**
 * Public response model with structured data (not JSON strings).
 */
export type CareerProfileRead = {
    /**
     * AI provider used: 'gemini' or 'ollama'
     */
    ai_provider: string;
    id: string;
    resume_id: string;
    owner_id: string;
    projects: Array<Project>;
    experience: Array<Experience>;
    skills: Array<SkillCategory>;
    extracted_at: string;
};

/**
 * Update model for career profile.
 * All fields are optional to allow partial updates.
 */
export type CareerProfileUpdate = {
    projects?: (Array<Project> | null);
    experience?: (Array<Experience> | null);
    skills?: (Array<SkillCategory> | null);
};

/**
 * Work experience entry from resume
 */
export type Experience = {
    /**
     * Company name
     */
    company: string;
    /**
     * Job title/role
     */
    role: string;
    /**
     * Time period, e.g., '2020-2023' or '2 years'
     */
    duration: string;
    /**
     * Key responsibilities and achievements
     */
    responsibilities: Array<(string)>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobCreate = {
    title: string;
    company: string;
    url: string;
    location: string;
    description: string;
};

export type JobPublic = {
    title: string;
    company: string;
    url: string;
    location: string;
    description: string;
    id: string;
    owner_id: string;
    status: string;
    created_at: (string | null);
    probing_questions: Array<ProbingQuestionPublic>;
};

export type JobsPublic = {
    data: Array<JobPublic>;
    count: number;
};

export type JobStats = {
    Draft?: number;
    Applied?: number;
    Shortlisted?: number;
    Interviewing?: number;
    Offered?: number;
    Redirected?: number;
    Waiting?: number;
};

export type JobUpdate = {
    title?: (string | null);
    company?: (string | null);
    url?: (string | null);
    location?: (string | null);
    description?: (string | null);
    status?: (string | null);
};

export type ProbingQuestionPublic = {
    question_text: string;
    answer?: (string | null);
    id: string;
    job_id: string;
};

export type ProbingQuestionUpdate = {
    answer: string;
};

export type ProbingQuestionsUpdateQuestionData = {
    id: string;
    requestBody: ProbingQuestionUpdate;
};

export type ProbingQuestionsUpdateQuestionResponse = (ProbingQuestionPublic);

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Individual project extracted from resume
 */
export type Project = {
    /**
     * Project name or title
     */
    title: string;
    /**
     * Brief description of what was built
     */
    description: string;
    /**
     * Technologies, languages, frameworks used
     */
    technologies: Array<(string)>;
    /**
     * Business impact or metrics if mentioned
     */
    impact?: (string | null);
};

export type ResumePublic = {
    filename: string;
    raw_text: string;
    id: string;
    owner_id: string;
    upload_date: (string | null);
};

export type ResumesPublic = {
    data: Array<ResumePublic>;
    count: number;
};

/**
 * Categorized skills from resume
 */
export type SkillCategory = {
    /**
     * Skill category, e.g., 'Backend', 'Frontend', 'DevOps'
     */
    category: string;
    /**
     * List of skills in this category
     */
    skills: Array<(string)>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsReadJobStatsResponse = (JobStats);

export type JobsReadJobsData = {
    limit?: number;
    skip?: number;
};

export type JobsReadJobsResponse = (JobsPublic);

export type JobsCreateJobData = {
    requestBody: JobCreate;
};

export type JobsCreateJobResponse = (JobPublic);

export type JobsReadJobData = {
    id: string;
};

export type JobsReadJobResponse = (JobPublic);

export type JobsUpdateJobData = {
    id: string;
    requestBody: JobUpdate;
};

export type JobsUpdateJobResponse = (JobPublic);

export type JobsDeleteJobData = {
    id: string;
};

export type JobsDeleteJobResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfilesReadResumeProfileData = {
    id: string;
};

export type ProfilesReadResumeProfileResponse = (CareerProfileRead);

export type ProfilesUpdateResumeProfileData = {
    id: string;
    requestBody: CareerProfileUpdate;
};

export type ProfilesUpdateResumeProfileResponse = (CareerProfileRead);

export type ResumesUploadResumeData = {
    formData: Body_resumes_upload_resume;
};

export type ResumesUploadResumeResponse = (ResumePublic);

export type ResumesReadResumesData = {
    limit?: number;
    skip?: number;
};

export type ResumesReadResumesResponse = (ResumesPublic);

export type ResumesReadResumeData = {
    resumeId: string;
};

export type ResumesReadResumeResponse = (ResumePublic);

export type ResumesDeleteResumeData = {
    resumeId: string;
};

export type ResumesDeleteResumeResponse = (Message);

export type ResumesExtractCareerProfileData = {
    resumeId: string;
};

export type ResumesExtractCareerProfileResponse = (CareerProfilePublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = ({
    [key: string]: (string);
});