"""Add token_version to User

Revision ID: 6cb1db3025f1
Revises: f8b981eaaf4e
Create Date: 2026-02-13 09:26:08.401255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cb1db3025f1'
down_revision = 'f8b981eaaf4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('careerprofile', 'projects',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('careerprofile', 'experience',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('careerprofile', 'skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('item', 'created_at')
    op.alter_column('job', 'url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sqlmodel.sql.sqltypes.AutoString(length=512),
               existing_nullable=True)
    op.drop_column('job', 'updated_at')
    op.add_column('user', sa.Column('token_version', sa.Integer(), nullable=True))
    op.execute("UPDATE \"user\" SET token_version = 0")
    op.alter_column('user', 'token_version', nullable=False)
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user', 'token_version')
    op.add_column('job', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('job', 'url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.add_column('item', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('careerprofile', 'skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('careerprofile', 'experience',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('careerprofile', 'projects',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
