/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutResumesRouteImport } from './routes/_layout/resumes'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProfileIndexRouteImport } from './routes/_layout/profile/index'
import { Route as LayoutJobsIndexRouteImport } from './routes/_layout/jobs/index'
import { Route as LayoutJobsAddRouteImport } from './routes/_layout/jobs.add'
import { Route as LayoutResumesResumeIdProfileRouteImport } from './routes/_layout/resumes.$resumeId.profile'
import { Route as LayoutJobsJobIdAnalysisRouteImport } from './routes/_layout/jobs.$jobId.analysis'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResumesRoute = LayoutResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobsIndexRoute = LayoutJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobsAddRoute = LayoutJobsAddRouteImport.update({
  id: '/jobs/add',
  path: '/jobs/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResumesResumeIdProfileRoute =
  LayoutResumesResumeIdProfileRouteImport.update({
    id: '/$resumeId/profile',
    path: '/$resumeId/profile',
    getParentRoute: () => LayoutResumesRoute,
  } as any)
const LayoutJobsJobIdAnalysisRoute = LayoutJobsJobIdAnalysisRouteImport.update({
  id: '/jobs/$jobId/analysis',
  path: '/jobs/$jobId/analysis',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/resumes': typeof LayoutResumesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/jobs/add': typeof LayoutJobsAddRoute
  '/jobs/': typeof LayoutJobsIndexRoute
  '/profile/': typeof LayoutProfileIndexRoute
  '/jobs/$jobId/analysis': typeof LayoutJobsJobIdAnalysisRoute
  '/resumes/$resumeId/profile': typeof LayoutResumesResumeIdProfileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/resumes': typeof LayoutResumesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/jobs/add': typeof LayoutJobsAddRoute
  '/jobs': typeof LayoutJobsIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/jobs/$jobId/analysis': typeof LayoutJobsJobIdAnalysisRoute
  '/resumes/$resumeId/profile': typeof LayoutResumesResumeIdProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/resumes': typeof LayoutResumesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/jobs/add': typeof LayoutJobsAddRoute
  '/_layout/jobs/': typeof LayoutJobsIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/jobs/$jobId/analysis': typeof LayoutJobsJobIdAnalysisRoute
  '/_layout/resumes/$resumeId/profile': typeof LayoutResumesResumeIdProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/resumes'
    | '/settings'
    | '/jobs/add'
    | '/jobs/'
    | '/profile/'
    | '/jobs/$jobId/analysis'
    | '/resumes/$resumeId/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/resumes'
    | '/settings'
    | '/'
    | '/jobs/add'
    | '/jobs'
    | '/profile'
    | '/jobs/$jobId/analysis'
    | '/resumes/$resumeId/profile'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/resumes'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/jobs/add'
    | '/_layout/jobs/'
    | '/_layout/profile/'
    | '/_layout/jobs/$jobId/analysis'
    | '/_layout/resumes/$resumeId/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resumes': {
      id: '/_layout/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof LayoutResumesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jobs/': {
      id: '/_layout/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof LayoutJobsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jobs/add': {
      id: '/_layout/jobs/add'
      path: '/jobs/add'
      fullPath: '/jobs/add'
      preLoaderRoute: typeof LayoutJobsAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resumes/$resumeId/profile': {
      id: '/_layout/resumes/$resumeId/profile'
      path: '/$resumeId/profile'
      fullPath: '/resumes/$resumeId/profile'
      preLoaderRoute: typeof LayoutResumesResumeIdProfileRouteImport
      parentRoute: typeof LayoutResumesRoute
    }
    '/_layout/jobs/$jobId/analysis': {
      id: '/_layout/jobs/$jobId/analysis'
      path: '/jobs/$jobId/analysis'
      fullPath: '/jobs/$jobId/analysis'
      preLoaderRoute: typeof LayoutJobsJobIdAnalysisRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutResumesRouteChildren {
  LayoutResumesResumeIdProfileRoute: typeof LayoutResumesResumeIdProfileRoute
}

const LayoutResumesRouteChildren: LayoutResumesRouteChildren = {
  LayoutResumesResumeIdProfileRoute: LayoutResumesResumeIdProfileRoute,
}

const LayoutResumesRouteWithChildren = LayoutResumesRoute._addFileChildren(
  LayoutResumesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutResumesRoute: typeof LayoutResumesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutJobsAddRoute: typeof LayoutJobsAddRoute
  LayoutJobsIndexRoute: typeof LayoutJobsIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutJobsJobIdAnalysisRoute: typeof LayoutJobsJobIdAnalysisRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutResumesRoute: LayoutResumesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutJobsAddRoute: LayoutJobsAddRoute,
  LayoutJobsIndexRoute: LayoutJobsIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutJobsJobIdAnalysisRoute: LayoutJobsJobIdAnalysisRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
